// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ArcRPM = NULL;
lv_obj_t * ui_ArcSpeed = NULL;
lv_obj_t * ui_NameRPM = NULL;
lv_obj_t * ui_NameSpeed = NULL;
lv_obj_t * ui_BarBoost = NULL;
lv_obj_t * ui_LabelBoost = NULL;
lv_obj_t * ui_LabelRPM = NULL;
lv_obj_t * ui_LabelSpeed = NULL;
lv_obj_t * ui_ArcTemp = NULL;
lv_obj_t * ui_LabelTemp = NULL;
lv_obj_t * ui_LabelBoost1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcRPM = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcRPM, 140);
    lv_obj_set_height(ui_ArcRPM, 140);
    lv_obj_set_x(ui_ArcRPM, -76);
    lv_obj_set_y(ui_ArcRPM, -46);
    lv_obj_set_align(ui_ArcRPM, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcRPM, 0, 5000);
    lv_arc_set_value(ui_ArcRPM, 0);

    ui_ArcSpeed = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcSpeed, 140);
    lv_obj_set_height(ui_ArcSpeed, 140);
    lv_obj_set_x(ui_ArcSpeed, 76);
    lv_obj_set_y(ui_ArcSpeed, -46);
    lv_obj_set_align(ui_ArcSpeed, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcSpeed, 0, 220);
    lv_arc_set_value(ui_ArcSpeed, 0);

    ui_NameRPM = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_NameRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameRPM, -76);
    lv_obj_set_y(ui_NameRPM, 0);
    lv_obj_set_align(ui_NameRPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NameRPM, "RPM");

    ui_NameSpeed = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_NameSpeed, LV_SIZE_CONTENT);   /// 66
    lv_obj_set_height(ui_NameSpeed, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_NameSpeed, 76);
    lv_obj_set_y(ui_NameSpeed, 0);
    lv_obj_set_align(ui_NameSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NameSpeed, "KMH");

    ui_BarBoost = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_BarBoost, 0, 120);
    lv_bar_set_value(ui_BarBoost, 0, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarBoost, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarBoost, 150);
    lv_obj_set_height(ui_BarBoost, 10);
    lv_obj_set_x(ui_BarBoost, -76);
    lv_obj_set_y(ui_BarBoost, 52);
    lv_obj_set_align(ui_BarBoost, LV_ALIGN_CENTER);

    ui_LabelBoost = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelBoost, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBoost, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBoost, -108);
    lv_obj_set_y(ui_LabelBoost, 75);
    lv_obj_set_align(ui_LabelBoost, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBoost, "Tlak Turba");

    ui_LabelRPM = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRPM, -76);
    lv_obj_set_y(ui_LabelRPM, -49);
    lv_obj_set_align(ui_LabelRPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRPM, "XXXX");

    ui_LabelSpeed = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSpeed, LV_SIZE_CONTENT);   /// 66
    lv_obj_set_height(ui_LabelSpeed, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_LabelSpeed, 76);
    lv_obj_set_y(ui_LabelSpeed, -49);
    lv_obj_set_align(ui_LabelSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed, "XXX");

    ui_ArcTemp = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcTemp, 99);
    lv_obj_set_height(ui_ArcTemp, 99);
    lv_obj_set_x(ui_ArcTemp, 76);
    lv_obj_set_y(ui_ArcTemp, 65);
    lv_obj_set_align(ui_ArcTemp, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcTemp, 50, 120);
    lv_arc_set_value(ui_ArcTemp, 0);

    ui_LabelTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, 76);
    lv_obj_set_y(ui_LabelTemp, 62);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "XX°C");


    ui_LabelBoost1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelBoost1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBoost1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBoost1, -32);
    lv_obj_set_y(ui_LabelBoost1, 75);
    lv_obj_set_align(ui_LabelBoost1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBoost1, "X.x Kpa");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ArcRPM = NULL;
    ui_ArcSpeed = NULL;
    ui_NameRPM = NULL;
    ui_NameSpeed = NULL;
    ui_BarBoost = NULL;
    ui_LabelBoost = NULL;
    ui_LabelRPM = NULL;
    ui_LabelSpeed = NULL;
    ui_ArcTemp = NULL;
    ui_LabelTemp = NULL;
    ui_LabelBoost1 = NULL;

}
