// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ArcRPM;
extern lv_obj_t * ui_ArcSpeed;
extern lv_obj_t * ui_NameRPM;
extern lv_obj_t * ui_NameSpeed;
extern lv_obj_t * ui_BarBoost;
extern lv_obj_t * ui_LabelBoost;
extern lv_obj_t * ui_LabelRPM;
extern lv_obj_t * ui_LabelSpeed;
extern lv_obj_t * ui_ArcTemp;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_LabelBoost1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

